package com.mx.sda.util;

public enum PermisosRol {

	READ_ALL_GRUPOS,
	READ_ONE_GRUPOS,
	CREATE_ONE_GRUPOS,
	UPDATE_ONE_GRUPOS,
	DISABLE_ONE_GRUPOS,
	
	READ_ALL_ALUMNOS,
	READ_ONE_ALUMNOS,
	CREATE_ONE_ALUMNOS,
	UPDATE_ONE_ALUMNOS,
	DISABLE_ONE_ALUMNOS,
	
	READ_ALL_DOCENTES,
	READ_ONE_DOCENTES,
	CREATE_ONE_DOCENTES,
	UPDATE_ONE_DOCENTES,
	DISABLE_ONE_DOCENTES;
	
}
